name: Issue label

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:



  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.https://github.com/Laxmirabari/Cloudbuild/issues/1#issue-1657799930}}
        run:
          gh issue edit $ISSUE_URL --add-label "triage"
